# Generated by Django 5.2 on 2025-05-06 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0002_transaction_destination_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('LTC', 'Litecoin'), ('XRP', 'Ripple'), ('ADA', 'Cardano'), ('SOL', 'Solana'), ('DOT', 'Polkadot'), ('BNB', 'Binance Coin'), ('DOGE', 'Dogecoin'), ('LINK', 'Chainlink'), ('MATIC', 'Polygon'), ('EOS', 'EOS.IO')], max_length=10, unique=True)),
                ('wallet_address', models.CharField(max_length=255)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_asset_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='staking.assetwallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='staking.assetwallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('STAKE', 'Stake'), ('UNSTAKE', 'Unstake'), ('REWARD', 'Reward'), ('SWAP', 'Swap')], max_length=10),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_asset', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('LTC', 'Litecoin'), ('XRP', 'Ripple'), ('ADA', 'Cardano'), ('SOL', 'Solana'), ('DOT', 'Polkadot'), ('BNB', 'Binance Coin'), ('DOGE', 'Dogecoin'), ('LINK', 'Chainlink'), ('MATIC', 'Polygon'), ('EOS', 'EOS.IO')], max_length=10)),
                ('to_asset', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('LTC', 'Litecoin'), ('XRP', 'Ripple'), ('ADA', 'Cardano'), ('SOL', 'Solana'), ('DOT', 'Polkadot'), ('BNB', 'Binance Coin'), ('DOGE', 'Dogecoin'), ('LINK', 'Chainlink'), ('MATIC', 'Polygon'), ('EOS', 'EOS.IO')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=12, max_digits=24)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('from_asset', 'to_asset')},
            },
        ),
    ]
