# Generated by Django 5.2 on 2025-05-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0003_depositaddress_transaction_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stake',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10),
        ),
    ]
